# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$ocaml\
$java\
$python\
$lua\
$docker_context\
$cmd_duration\
$line_break$character
"""

palette = 'custom'

[palettes.custom]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#00ccff'
color_green = '#11cc00'
color_orange = '#ff9900'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_white='#fefefe'
color_turquoise='#40e0d0'
color_char_green='#6bf740'
color_char_red='#e66a6a'

mocha_blue = '#89b4fa'
mocha_green = '#a6e3a1'
mocha_red = '#f38ba8'
mocha_mauve = '#cba6f7'
mocha_rosewater = '#f5e0dc'
mocha_peach = '#fab387'

# For funsies
[character]
success_symbol = '[](color_char_green)'
error_symbol = '[](color_char_red)'

# Make fill symbol blank (space)
[fill]
symbol = ' '

[os]
disabled = false
style = "fg:color_white"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
Macos = "󰀵 "
Linux = "󰌽 "
Amazon = " "
Android = " "
Arch = "󰣇 "
Debian = "󰣚 "

[directory]
style = "fg:color_aqua"
format = "[$path ]($style)"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = '[[$symbol$branch ](fg:color_green)]($style)'

[git_status]
format = '[[(\[$all_status$ahead_behind\] )](fg:color_orange)]($style)'

[c]
symbol = "  "
format = '[[$symbol($version) ](fg:color_turquoise)]($style)'

[rust]
symbol = "  "
format = '[[$symbol($version) ](fg:color_turquoise)]($style)'

[golang]
symbol = " "
format = '[[$symbol($version) ](fg:color_turquoise)]($style)'

[ocaml]
symbol = " "
format = '[[$symbol($version) ](fg:color_turquoise)]($style)'

[java]
symbol = " "
format = '[[$symbol($version) ](fg:mocha_mauve)]($style)'

[python]
symbol = " "
format = '[[$symbol($version) ](fg:mocha_mauve)]($style)'

[lua]
symbol = " "
format = '[[$symbol($version) ](fg:color_turquoise)]($style)'

[docker_context]
symbol = " "
format = '[[$symbol($context) ](fg:#1ad1ff)]($style)'

[cmd_duration]
format = 'took [$duration]($style)'

[time]
disabled = false
use_12hr = true
format = '[[  $time](fg:color_fg0)]($style)'

[line_break]
disabled = false
